# Generated by Django 3.2.15 on 2022-09-15 12:40

from django.db import migrations, models
import task.validators


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, validators=[task.validators.datetime_must_be_in_futur]),
        ),
    ]
